### ISSUE TITLE
Morale filter is filtering by "less than" instead of "greater than"

### ISSUE THREAD

**Issue by kazenorin** [Javran/poi-plugin-mo2#1]
Not sure if this is the intended behavior or not, but isn't finding ships that are sparkling more useful?

**Comment by Javran** [comment]
it's intended as this part of the plugin is more of finding ships to sparkle than finding already sparkled ships. But I don't think it hurts to have some "greater than" filters - consider this to be part of the next version.

**Comment by Javran** [comment]
Just released new version (0.5.0), now it's possible to use "less than" / "less then or equal to" / "greater than" / "greater than or equal to" / "equal to" filters.

**Comment by kazenorin** [comment]
I've just updated, but getting this error:
`TypeError: Cannot read property 'map' of undefined
    at ShipMoraleListImpl.render (C:/Users/username/AppData/Roaming/poi/plugins/node_modules/poi-plugin-mo2/ui/ship-morale-list/index.es:231:29)
    at h (C:\Users\username\AppData\Local\Programs\poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:130:280)
    at beginWork (C:\Users\username\AppData\Local\Programs\poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:133:485)
    at d (C:\Users\username\AppData\Local\Programs\poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:161:93)
    at f (C:\Users\username\AppData\Local\Programs\poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:161:417)
    at g (C:\Users\username\AppData\Local\Programs\poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:162:149)
    at m (C:\Users\username\AppData\Local\Programs\poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:169:173)
    at w (C:\Users\username\AppData\Local\Programs\poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:168:413)
    at z (C:\Users\username\AppData\Local\Programs\poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:167:32)
    at u (C:\Users\username\AppData\Local\Programs\poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:165:441)
    at Object.enqueueSetState (C:\Users\username\AppData\Local\Programs\poi\resources\app\node_modules\react-dom\cjs\react-dom.production.min.js:108:299)
    at Connect.A.setState (C:\Users\username\AppData\Local\Programs\poi\resources\app\node_modules\react\cjs\react.production.min.js:12:357)
    at Connect.onStateChange (C:\Users\username\AppData\Local\Programs\poi\resources\app\node_modules\react-redux\lib\components\connectAdvanced.js:222:16)
    at Object.notify (C:\Users\username\AppData\Local\Programs\poi\resources\app\node_modules\react-redux\lib\utils\Subscription.js:30:21)
    at Subscription.notifyNestedSubs (C:\Users\username\AppData\Local\Programs\poi\resources\app\node_modules\react-redux\lib\utils\Subscription.js:69:20)
    at Connect.onStateChange (C:\Users\username\AppData\Local\Programs\poi\resources\app\node_modules\react-redux\lib\components\connectAdvanced.js:219:16)
    at Object.notify (C:\Users\username\AppData\Local\Programs\poi\resources\app\node_modules\react-redux\lib\utils\Subscription.js:30:21)
    at Subscription.notifyNestedSubs (C:\Users\username\AppData\Local\Programs\poi\resources\app\node_modules\react-redux\lib\utils\Subscription.js:69:20)
    at Connect.onStateChange (C:\Users\username\AppData\Local\Programs\poi\resources\app\node_modules\react-redux\lib\components\connectAdvanced.js:219:16)
    at Object.notify (C:\Users\username\AppData\Local\Programs\poi\resources\app\node_modules\react-redux\lib\utils\Subscription.js:30:21)
    at Subscription.notifyNestedSubs (C:\Users\username\AppData\Local\Programs\poi\resources\app\node_modules\react-redux\lib\utils\Subscription.js:69:20)
    at Connect.onStateChange (C:\Users\username\AppData\Local\Programs\poi\resources\app\node_modules\react-redux\lib\components\connectAdvanced.js:219:16)
    at dispatch (C:\Users\username\AppData\Local\Programs\poi\resources\app\node_modules\redux\lib\createStore.js:186:7)
    at Object.replaceReducer (C:\Users\username\AppData\Local\Programs\poi\resources\app\node_modules\redux\lib\createStore.js:208:5)
    at C:\Users\username\AppData\Local\Programs\poi\resources\app\views\create-store.js:133:13
    at postEnableProcess (C:\Users\username\AppData\Local\Programs\poi\resources\app\views\services\plugin-manager-utils.js:398:38)
    at _ref16 (C:\Users\username\AppData\Local\Programs\poi\resources\app\views\services\plugin-manager-utils.js:381:12)
    at _ref16.next (<anonymous>)
    at step (C:\Users\username\AppData\Local\Programs\poi\resources\app\views\services\plugin-manager-utils.js:119:191)
    at C:\Users\username\AppData\Local\Programs\poi\resources\app\views\services\plugin-manager-utils.js:119:361
    at tryCatcher (C:\Users\username\AppData\Local\Programs\poi\resources\app\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\username\AppData\Local\Programs\poi\resources\app\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\username\AppData\Local\Programs\poi\resources\app\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\username\AppData\Local\Programs\poi\resources\app\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\username\AppData\Local\Programs\poi\resources\app\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\username\AppData\Local\Programs\poi\resources\app\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\username\AppData\Local\Programs\poi\resources\app\node_modules\bluebird\js\release\async.js:143:10)
    at Async.drainQueues (C:\Users\username\AppData\Local\Programs\poi\resources\app\node_modules\bluebird\js\release\async.js:17:14)
    at <anonymous>

    in ShipMoraleListImpl
    in Connect(ShipMoraleListImpl)
    in div
    in TabPane
    in Tab
    in div
    in TabContent
    in div
    in TabContainer
    in Tabs
    in Uncontrolled(Tabs)
    in div
    in MoraleMonitorImpl
    in Connect(MoraleMonitorImpl)
    in div
    in PluginWrap
    in div
    in div
    in div
    in tabContentsUnion
    in Connect(tabContentsUnion)
    in div
    in ControlledTabArea
    in Connect(ControlledTabArea)
    in Provider`

**Comment by Javran** [comment]
@kazenorin can you open devtools and see if any error message is present?

also please try following two commands (one at a time) in console and let me know what the output looks like:

```javascript
> getStore().ext['poi-plugin-mo2']._.ready
> JSON.stringify(getStore().ext['poi-plugin-mo2']._.ships.filter.methods)
```

**Comment by Javran** [comment]
For a quick fix, just head to `%APPDATA%/poi/morale-monitor`, there should be a file named `<some-number>.json`, rename it to something else and reload the plugin should fix the problem. But you'll lost all your settings of this plugin. It could be that I messed up somewhere when updating internal data structure to new version.

Also could you paste the content of that `<some-number>.json`? That should help in my investigation. (don't paste the file name though, as the number is your admiral id)

**Comment by Javran** [comment]
just to make it more clear that by "reload the plugin" I mean disabling it and enabling it again.

**Comment by kazenorin** [comment]
Unfortunately (or fortunately?), I disabled and re-enabled the plugin first and the plugin seems to had fixed itself. I couldn't capture the error nor run the two commands when it didn't work.

I did not remove or rename \<admiral-id\>.json .

The content of my \<admiral-id\>.json is:

`{"fleets":{"watchlist":[]},"ships":{"sort":{"method":"morale","reversed":true},"filter":{"lessThanArr":[50,53,76,85,100],"stypeExt":"stype-2","moraleFilters":{"dlc-dd":"lt-50","dlc":"lt-100","sub":"all"}}},"tab":"ship","configVersion":"0.4.0"}`

This file was last modified on 17th Jan, 2018.

Right now, working normally, there are no relevant errors from the devtools console.  

> getStore().ext['poi-plugin-mo2']._.ready  

this is `true` now

> JSON.stringify(getStore().ext['poi-plugin-mo2']._.ships.filter.methods)

`"[{"type":"lessThan","value":50},{"type":"lessThan","value":53},{"type":"lessThan","value":76},{"type":"lessThan","value":85},{"type":"lessThan","value":100}]"`

**Comment by Javran** [comment]
Got it, the output all looks fine to me. I'm closing this issue as everything seems to work normally now.
