### ISSUE TITLE
plugin malfunctioned

### ISSUE THREAD

**Issue by YijieDeng** [Javran/poi-plugin-mo2#2]
插件[士气速查]变成了 乌龟图标...
不知道发生什么了，附上error

TypeError: undefined is not a function
    at Array.filter (<anonymous>)
    at stypeFilter (C:\Users\d9563\AppData\Roaming\poi\plugins\node_modules\poi-plugin-mo2/C:\Users\d9563\AppData\Roaming\poi\plugins\node_modules\poi-plugin-mo2\shiplist-ops.es:41:32)
    at C:\Users\d9563\Pictures\POI\poi-9.0.0-beta.0-win\resources\app.asar\node_modules\lodash\lodash.js:5157:35
    at shipMoraleListSelector (C:\Users\d9563\AppData\Roaming\poi\plugins\node_modules\poi-plugin-mo2\ui\ship-morale-list/C:\Users\d9563\AppData\Roaming\poi\plugins\node_modules\poi-plugin-mo2\ui\ship-morale-list\selectors.es:51:9)
    at C:\Users\d9563\Pictures\POI\poi-9.0.0-beta.0-win\resources\app.asar\node_modules\reselect\lib\index.js:76:25
    at C:\Users\d9563\Pictures\POI\poi-9.0.0-beta.0-win\resources\app.asar\node_modules\reselect\lib\index.js:36:25
    at C:\Users\d9563\Pictures\POI\poi-9.0.0-beta.0-win\resources\app.asar\node_modules\reselect\lib\index.js:90:33
    at C:\Users\d9563\Pictures\POI\poi-9.0.0-beta.0-win\resources\app.asar\node_modules\reselect\lib\index.js:36:25
    at Function.state [as mapToProps] (C:\Users\d9563\AppData\Roaming\poi\plugins\node_modules\poi-plugin-mo2\ui\ship-morale-list/C:\Users\d9563\AppData\Roaming\poi\plugins\node_modules\poi-plugin-mo2\ui\ship-morale-list\index.es:266:19)
    at mapToPropsProxy (C:\Users\d9563\Pictures\POI\poi-9.0.0-beta.0-win\resources\app.asar\node_modules\react-redux\lib\connect\wrapMapToProps.js:54:92)
    at handleNewState (C:\Users\d9563\Pictures\POI\poi-9.0.0-beta.0-win\resources\app.asar\node_modules\react-redux\lib\connect\selectorFactory.js:63:26)
    at handleSubsequentCalls (C:\Users\d9563\Pictures\POI\poi-9.0.0-beta.0-win\resources\app.asar\node_modules\react-redux\lib\connect\selectorFactory.js:80:30)
    at pureFinalPropsSelector (C:\Users\d9563\Pictures\POI\poi-9.0.0-beta.0-win\resources\app.asar\node_modules\react-redux\lib\connect\selectorFactory.js:85:32)
    at Object.runComponentSelector (C:\Users\d9563\Pictures\POI\poi-9.0.0-beta.0-win\resources\app.asar\node_modules\react-redux\lib\components\connectAdvanced.js:43:25)
    at Connect.onStateChange (C:\Users\d9563\Pictures\POI\poi-9.0.0-beta.0-win\resources\app.asar\node_modules\react-redux\lib\components\connectAdvanced.js:216:23)
    at Object.notify (C:\Users\d9563\Pictures\POI\poi-9.0.0-beta.0-win\resources\app.asar\node_modules\react-redux\lib\utils\Subscription.js:30:21)
    at Subscription.notifyNestedSubs (C:\Users\d9563\Pictures\POI\poi-9.0.0-beta.0-win\resources\app.asar\node_modules\react-redux\lib\utils\Subscription.js:69:20)
    at Connect.onStateChange (C:\Users\d9563\Pictures\POI\poi-9.0.0-beta.0-win\resources\app.asar\node_modules\react-redux\lib\components\connectAdvanced.js:219:16)
    at Object.notify (C:\Users\d9563\Pictures\POI\poi-9.0.0-beta.0-win\resources\app.asar\node_modules\react-redux\lib\utils\Subscription.js:30:21)
    at Subscription.notifyNestedSubs (C:\Users\d9563\Pictures\POI\poi-9.0.0-beta.0-win\resources\app.asar\node_modules\react-redux\lib\utils\Subscription.js:69:20)
    at Connect.onStateChange (C:\Users\d9563\Pictures\POI\poi-9.0.0-beta.0-win\resources\app.asar\node_modules\react-redux\lib\components\connectAdvanced.js:219:16)
    at Object.notify (C:\Users\d9563\Pictures\POI\poi-9.0.0-beta.0-win\resources\app.asar\node_modules\react-redux\lib\utils\Subscription.js:30:21)
    at Subscription.notifyNestedSubs (C:\Users\d9563\Pictures\POI\poi-9.0.0-beta.0-win\resources\app.asar\node_modules\react-redux\lib\utils\Subscription.js:69:20)
    at Connect.notifyNestedSubsOnComponentDidUpdate (C:\Users\d9563\Pictures\POI\poi-9.0.0-beta.0-win\resources\app.asar\node_modules\react-redux\lib\components\connectAdvanced.js:233:14)
    at commitLifeCycles (C:\Users\d9563\Pictures\POI\poi-9.0.0-beta.0-win\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:158:207)
    at R (C:\Users\d9563\Pictures\POI\poi-9.0.0-beta.0-win\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:184:7)
    at G (C:\Users\d9563\Pictures\POI\poi-9.0.0-beta.0-win\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:181:349)
    at x (C:\Users\d9563\Pictures\POI\poi-9.0.0-beta.0-win\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:180:378)
    at n (C:\Users\d9563\Pictures\POI\poi-9.0.0-beta.0-win\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:180:221)
    at B (C:\Users\d9563\Pictures\POI\poi-9.0.0-beta.0-win\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:179:117)
    at v (C:\Users\d9563\Pictures\POI\poi-9.0.0-beta.0-win\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:178:51)
    at Object.enqueueSetState (C:\Users\d9563\Pictures\POI\poi-9.0.0-beta.0-win\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:109:32)
    at Connect.D.setState (C:\Users\d9563\Pictures\POI\poi-9.0.0-beta.0-win\resources\app.asar\node_modules\react\cjs\react.production.min.js:12:357)
    at Connect.onStateChange (C:\Users\d9563\Pictures\POI\poi-9.0.0-beta.0-win\resources\app.asar\node_modules\react-redux\lib\components\connectAdvanced.js:222:16)
    at Object.notify (C:\Users\d9563\Pictures\POI\poi-9.0.0-beta.0-win\resources\app.asar\node_modules\react-redux\lib\utils\Subscription.js:30:21)
    at Subscription.notifyNestedSubs (C:\Users\d9563\Pictures\POI\poi-9.0.0-beta.0-win\resources\app.asar\node_modules\react-redux\lib\utils\Subscription.js:69:20)
    at Connect.onStateChange (C:\Users\d9563\Pictures\POI\poi-9.0.0-beta.0-win\resources\app.asar\node_modules\react-redux\lib\components\connectAdvanced.js:219:16)
    at Object.notify (C:\Users\d9563\Pictures\POI\poi-9.0.0-beta.0-win\resources\app.asar\node_modules\react-redux\lib\utils\Subscription.js:30:21)
    at Subscription.notifyNestedSubs (C:\Users\d9563\Pictures\POI\poi-9.0.0-beta.0-win\resources\app.asar\node_modules\react-redux\lib\utils\Subscription.js:69:20)
    at Connect.onStateChange (C:\Users\d9563\Pictures\POI\poi-9.0.0-beta.0-win\resources\app.asar\node_modules\react-redux\lib\components\connectAdvanced.js:219:16)
    at dispatch (C:\Users\d9563\Pictures\POI\poi-9.0.0-beta.0-win\resources\app.asar\node_modules\redux\lib\redux.js:227:7)
    at C:\Users\d9563\Pictures\POI\poi-9.0.0-beta.0-win\resources\app.asar\node_modules\redux-thunk\lib\index.js:14:16
    at action (C:\Users\d9563\Pictures\POI\poi-9.0.0-beta.0-win\resources\app.asar\views\middlewares\promise-action.js:55:12)
    at Object.pStateLoaded (C:\Users\d9563\Pictures\POI\poi-9.0.0-beta.0-win\resources\app.asar\node_modules\redux\lib\redux.js:455:12)
    at setTimeout (C:\Users\d9563\AppData\Roaming\poi\plugins\node_modules\poi-plugin-mo2\observers/C:\Users\d9563\AppData\Roaming\poi\plugins\node_modules\poi-plugin-mo2\observers\p-state-loader.es:35:13)

    in Connect(ShipMoraleListImpl)
    in div
    in TabPane
    in Tab
    in div
    in TabContent
    in div
    in TabContainer
    in Tabs
    in Uncontrolled(Tabs)
    in div
    in MoraleMonitorImpl
    in Connect(MoraleMonitorImpl)
    in div
    in PluginWrap
    in I18n
    in Translate(PluginWrap)
    in div
    in div
    in div
    in TabContentsUnion
    in Connect(TabContentsUnion)
    in div
    in div
    in t
    in div
    in ControlledTabArea
    in Connect(ControlledTabArea)
    in I18n
    in Translate(Connect(ControlledTabArea))
    in poi-nav-tabs
    in poi-nav
    in div
    in poi-app
    in PoiApp
    in Connect(PoiApp)
    in poi-main
    in Poi
    in Connect(Poi)
    in Provider
    in I18nextProvider

**Comment by Javran** [comment]
打开目录 `%APPDATA\poi\morale-monitor` 下面应该有个文件是 `<数字>.json`, 打开那个文件把里面的内容发一下. (那个数字我不需要知道)
另外把那个文件重命名一下应该就能解决问题.

**Comment by YijieDeng** [comment]
谢谢，重命名后解决了

{"$version":"0.5.0","fleets":{},"ships":{"sort":{},"filter":{"methods":[{"type":"lessThan","value":50},{"type":"lessThan","value":53},{"type":"lessThan","value":76},{"type":"lessThan","value":85},{"type":"lessThan","value":100}],"moraleFilters":{}}},"tab":"fleet"}

**Comment by Javran** [comment]
@PracticeU 还记得是从什么版本升级到0.5.0的吗? 0.4.x 或者是更早的版本?

**Comment by YijieDeng** [comment]
这个真不记得...

**Comment by Javran** [comment]
关闭过期issue. 遇到类似问题可以尝试重命名或删除目录 `%APPDATA\poi\morale-monitor`.
